#!/usr/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
cd "${DIR}"
export LD_LIBRARY_PATH="${DIR}"
export DSM_DIR="${DIR}"
#echo $LD_LIBRARY_PATH
#echo $DSM_DIR
"${DIR}"/dsmadmc.exe "$@"
